# Generated by Django 6.0.1 on 2026-01-18 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('character', models.CharField(help_text='Nama karakter yang berbicara', max_length=100)),
                ('text', models.TextField(help_text='Teks dialog (gunakan ... untuk jeda berpikir)')),
                ('next_node', models.CharField(blank=True, help_text='Node ID untuk lanjutan otomatis', max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NarrativeStory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('main_character', models.CharField(choices=[('pitung', 'Si Pitung'), ('maknani', 'Mak Nani'), ('bandudin', 'Bang Udin'), ('kampung', 'Kampung')], max_length=20)),
                ('moral_message', models.TextField(help_text='Pesan moral dari cerita')),
                ('play_count', models.IntegerField(default=0)),
                ('average_duration', models.IntegerField(default=0, help_text='Durasi rata-rata dalam detik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Narrative Stories',
            },
        ),
        migrations.CreateModel(
            name='DialogChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Teks pilihan jawaban', max_length=255)),
                ('next_node', models.CharField(help_text='Node ID tujuan', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='peta.dialognode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dialognode',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_nodes', to='peta.narrativestory'),
        ),
        migrations.CreateModel(
            name='CultureLocation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pusat_budaya', 'Pusat Budaya'), ('tradisi_kuliner', 'Tradisi & Kuliner'), ('festival_sejarah', 'Festival & Sejarah')], max_length=20)),
                ('coord_x', models.FloatField(default=50)),
                ('coord_y', models.FloatField(default=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peta.narrativestory')),
            ],
            options={
                'verbose_name_plural': 'Culture Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dialognode',
            unique_together={('story', 'node_id')},
        ),
        migrations.CreateModel(
            name='StoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_played', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peta.dialognode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peta.narrativestory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'story')},
            },
        ),
    ]
